//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UUS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int journalID { get; set; }
        public Nullable<int> courceID { get; set; }
        public Nullable<int> studentID { get; set; }
        public Nullable<int> groupID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> semestr { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<System.DateTime> dateScore { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Group Groups { get; set; }
        public virtual Student Students { get; set; }
        public virtual User Users { get; set; }
    }
}
